defaults: &defaults
  working_directory: ~/artsy/reaction
  docker:
    - image: circleci/node:8
  
setup_job: &setup_job
  checkout: null
  restore_cache:
      keys:
      - yarn-deps-{{ checksum "yarn.lock" }}
      - yarn-deps-
  run: yarn --check-files

version: 2
jobs:
  relay:
    <<: *defaults
    docker:
    - image: circleci/node:8
    steps: 
      - <<: *setup_job
      - run: yarn relay
  lint:
    <<: *defaults
    steps: 
      - <<: *setup_job
      - run: yarn lint 
  type-check:
    <<: *defaults
    steps: 
      - <<: *setup_job
      - run: yarn type-check
  deploy:
    <<: *defaults
    steps:
      - <<: *setup_job
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: yarn semantic-release
      - run: cp .env.oss .env
      - run: yarn deploy-storybook
  test:
    <<: *defaults
    steps: 
      - <<: *setup_job
      - run: yarn test -w 4
  update-cache:
    <<: *defaults
    steps:
      - <<: *setup_job
      - save_cache:
          key: yarn-deps-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
workflows:
  version: 2
  build_and_verify:
    jobs:
      - update-cache
      - relay
      - lint
      - type-check
      - test
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - test
            - relay
            - lint
            - type-check
            - update-cache
