version: 2.1

orbs:
  node: artsy/node@0.0.1
  yarn: artsy/yarn@0.0.1
  queue: eddiewebb/queue@1.0.107

jobs:
  relay:
    executor: node/build
    steps:
      - yarn/setup
      - run: yarn relay
  lint:
    executor: node/build
    steps:
      - yarn/setup
      - run: yarn lint
  type-check:
    executor: node/build
    steps:
      - yarn/setup
      - run: yarn type-check
  deploy:
    executor: node/build
    # Deploy doesn't use yarn/setup intentially. It's assumed that update-cache
    # has already ran by the time deploy executes so the dependencies in the
    # cache should be up-to-date therefore not requiring check_and_install to be
    # executed
    steps:
      - checkout
      - yarn/load_dependencies
      # Setup the .npmrc with the proper registry and auth token to publish
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: yarn semantic-release
  queue:
    executor: node/build
    steps:
      - queue/until_front_of_line:
          time: "2" # Timeout after 2 minutes of waiting and fail the build
          consider-job: false # Block on entire workflow instead of just this job
          only-on-branch: master
  test:
    executor: node/build
    steps:
      - yarn/setup
      # Runs jest tests with 4 concurrent workers. Without limiting it to 4
      # workers Jest will spawn many memory hungry workers and ultimately
      # starve the job for memory.
      - run: yarn test -w 4
  update-cache:
    executor: node/build
    steps:
      - yarn/update_dependencies

workflows:
  build_and_verify:
    jobs:
      - update-cache:
          requires:
            - queue
      - relay:
          requires:
            - queue
      - lint:
          requires:
            - queue
      - type-check:
          requires:
            - queue
      - test:
          requires:
            - queue

      - queue:
          context: circleci-api

      - deploy:
          # The deploy job is the _only_ job that should have access to our npm
          # tokens. We include a context that has our publish credentials
          # explicitly in this step. https://circleci.com/docs/2.0/contexts/
          context: npm-deploy
          filters:
            branches:
              only:
                - master
          requires:
            - test
            - relay
            - lint
            - type-check
            - update-cache
