version: 2.1

orbs:
  yarn: artsy/yarn@dev:da826a2455c0d9f9ce31f71db9b0601e
  codecov: codecov/codecov@1.1.1
  auto: artsy/auto@1.3.2
  aws-s3: circleci/aws-s3@1.0.16

jobs:
  upload-storybook:
    docker:
      - image: "cimg/python:3.8"
    steps:
      - aws-s3/sync:
          arguments: --acl public-read
          from: storybook_build
          to: "s3://artsy-static-sites/artsy-reaction"

workflows:
  build_and_verify:
    jobs:
      - yarn/workflow-queue
      - yarn/update-cache:
          requires:
            - yarn/workflow-queue
      - yarn/relay:
          requires:
            - yarn/workflow-queue
      - yarn/run:
          name: lint-changed
          script: lint-changed
          requires:
            - yarn/workflow-queue
      - yarn/type-check:
          requires:
            - yarn/workflow-queue
      - yarn/jest:
          args: --runInBand
          only_test_changed: true
          notify_slack_on_failure: true
          context: slack-reaction-test-failures
          requires:
            - yarn/workflow-queue
          post-steps:
            - codecov/upload:
              file: coverage/lcov.info
      - auto/publish-canary:
          context: npm-deploy
          filters:
            branches:
              ignore:
                - master
          requires:
            - yarn/jest
            - yarn/relay
            - lint-changed
            - yarn/type-check
            - yarn/update-cache
      - auto/publish:
          context: npm-deploy
          filters:
            branches:
              only:
                - master
          requires:
            - yarn/jest
            - yarn/relay
            - lint-changed
            - yarn/type-check
            - yarn/update-cache
      - yarn/run:
          name: build-storybook
          script: "deploy-storybook"
          requires:
            - yarn/workflow-queue
          post-steps:
            - persist_to_workspace:
                root: .
                paths:
                  - storybook_build
          filters:
            branches:
              only: master
      - upload-storybook:
          context: static-sites-uploader
          requires:
            - yarn/workflow-queue
            - build-storybook
          pre-steps:
            - attach_workspace:
                at: .
          filters:
            branches:
              only: master
